import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Zap, Heart, FileQuestion, Cpu, ShieldCheck, Info } from 'lucide-react';

type WarningType = 'clickbait' | 'emotional' | 'missing-sources' | 'ai-generated' | 'well-supported';

interface WarningConfig {
  label: string;
  color: string;
  bg: string;
  border: string;
  icon: React.ElementType;
  explanation: string;
}

const WARNING_CONFIG: Record<WarningType, WarningConfig> = {
  'clickbait': {
    label: 'Clickbait',
    color: 'text-amber-400',
    bg: 'bg-amber-500/10',
    border: 'border-amber-500/30',
    icon: Zap,
    explanation: 'Headline uses sensationalist language to attract clicks without providing equivalent value.',
  },
  'emotional': {
    label: 'Emotional Language',
    color: 'text-purple-400',
    bg: 'bg-purple-500/10',
    border: 'border-purple-500/30',
    icon: Heart,
    explanation: 'Content relies on emotional appeals rather than factual evidence to persuade the reader.',
  },
  'missing-sources': {
    label: 'Missing Sources',
    color: 'text-rose-400',
    bg: 'bg-rose-500/10',
    border: 'border-rose-500/30',
    icon: FileQuestion,
    explanation: 'Significant claims are made without referencing credible primary sources or data.',
  },
  'ai-generated': {
    label: 'AI Generated',
    color: 'text-cyan-400',
    bg: 'bg-cyan-500/10',
    border: 'border-cyan-500/30',
    icon: Cpu,
    explanation: 'Patterns in the text suggest it was generated by an LLM without human oversight.',
  },
  'well-supported': {
    label: 'Well Supported',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    icon: ShieldCheck,
    explanation: 'Strong evidence and multiple credible sources support the main claims of the article.',
  },
};

const WarningBadge: React.FC<{ type: WarningType }> = ({ type }) => {
  const config = WARNING_CONFIG[type];
  const Icon = config.icon;
  const [showTooltip, setShowTooltip] = useState(false);

  return (
    <div className="relative group">
      <motion.div
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        onMouseEnter={() => setShowTooltip(true)}
        onMouseLeave={() => setShowTooltip(false)}
        className={`flex items-center gap-1.5 px-2.5 py-1 rounded-full border ${config.bg} ${config.border} ${config.color} cursor-help transition-all duration-200`}
      >
        <Icon className="w-3 h-3" />
        <span className="text-[11px] font-medium">{config.label}</span>
      </motion.div>

      <AnimatePresence>
        {showTooltip && (
          <motion.div
            initial={{ opacity: 0, y: 10, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 10, scale: 0.95 }}
            className="absolute z-50 bottom-full mb-2 left-1/2 -translate-x-1/2 w-48 p-2 rounded-lg bg-slate-900 border border-white/10 text-slate-300 text-[10px] leading-relaxed shadow-xl pointer-events-none"
          >
            <div className="flex items-start gap-1.5">
              <Info className="w-3 h-3 mt-0.5 shrink-0 text-slate-400" />
              <p>{config.explanation}</p>
            </div>
            {/* Tooltip Arrow */}
            <div className="absolute -bottom-1 left-1/2 -translate-x-1/2 w-2 h-2 bg-slate-900 border-r border-b border-white/10 rotate-45" />
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export const WarningBadges: React.FC<{ activeWarnings: WarningType[] }> = ({ activeWarnings }) => {
  if (activeWarnings.length === 0) return null;

  return (
    <div className="flex flex-wrap justify-center gap-2 py-2">
      {activeWarnings.map((type) => (
        <WarningBadge key={type} type={type} />
      ))}
    </div>
  );
};
